### ISSUE TITLE
[FR] Traefik integration

### ISSUE THREAD

**Issue by pyarmak** [Finsys/dockhand#2]
Consider integrating with Traefik labels.

Dockpeek's extraction: [https://github.com/dockpeek/dockpeek/blob/b98d8ec5b3db09a2a8b91dde590027e9934ed6cc/dockpeek/get_data.py#L20](https://github.com/dockpeek/dockpeek/blob/b98d8ec5b3db09a2a8b91dde590027e9934ed6cc/dockpeek/get_data.py#L20)

Dockpeek screenshot:
[https://github.com/dockpeek/dockpeek/blob/main/screenshots/screenshot_dark_v1.6.5.png](https://github.com/dockpeek/dockpeek/blob/main/screenshots/screenshot_dark_v1.6.5.png)

**Comment by strausmann** [comment]
Hey,
could you explain what the added value is if Dockhand can evaluate the Traefik labels? I didn't quite understand that.
Many thanks, Björn

**Comment by pyarmak** [comment]
@strausmann it's just a small QOL improvement to have the UI list the actual exposed traefik URL instead of just the internal port number. 
Obviously not critical but could be nice to get a sense of all the exposed traefik URLs at a glance and some edge cases like if you have forward auth configured on traefik for external access.

**Comment by jotka** [comment]
@pyarmak @strausmann ok

<img width="1317" height="317" alt="Image" src="https://github.com/user-attachments/assets/009d8e2a-d664-4e49-b83a-a604df57097d" />

<img width="1469" height="792" alt="Image" src="https://github.com/user-attachments/assets/fe510d43-aa62-4b01-9229-a9dc7656cd10" />

**Comment by strausmann** [comment]
Thank you for the implementation first. I know I'm a little late for this and the issue is currently dealing with traefik. But it would be possible on the train. The Pangolin Labels should also be included in this issue.

```yaml
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    labels:
      - pangolin.proxy-resources.grafana.name=Grafana
      - pangolin.proxy-resources.grafana.full-domain=grafana.example.com
      - pangolin.proxy-resources.grafana.protocol=http
      - pangolin.proxy-resources.grafana.auth.sso-enabled=true
      - pangolin.proxy-resources.grafana.targets[0].method=http
      - pangolin.proxy-resources.grafana.targets[0].port=3000

```

https://pangolin.net/news/blueprints

https://docs.pangolin.net/manage/blueprints#docker-compose-example

**Comment by jotka** [comment]
this is opt-in of course 

<img width="621" height="740" alt="Image" src="https://github.com/user-attachments/assets/aff447d6-449b-4796-bf32-a98ee7ec636d" />

**Comment by strausmann** [comment]
You are my hero

**Comment by jotka** [comment]
fixed in 

- fnsys/dockhand:v1.0.34
- fnsys/dockhand:latest
- fnsys/dockhand:v1.0.34-baseline
- fnsys/dockhand:latest-baseline
- fnsys/dockhand:baseline

**Comment by strausmann** [comment]
It seems we're still having a problem with the Pangolin labels.

According to the [Quick Start YAML Example](https://docs.pangolin.net/manage/blueprints#quick-start-yaml-example), the following labels are available:

- `pangolin.public-resources.<name>.full-domain`
- `pangolin.private-resources.<name>.full-domain`

When I read the description in the Settings, Dockhand currently checks for `pangolin.proxy-resources.<name>.full-domain`

Based on Pangolin’s documentation, I’m not sure if `proxy-resources` is used anywhere at all. At least, I can’t find anything when I search for it.

**Comment by jotka** [comment]
@strausmann I'm looking into it.

**Comment by jotka** [comment]
@strausmann please test 1.0.35 RC: `fnsys/dockhand:698768b6`

**Comment by strausmann** [comment]
Hey, looks very good. Thank you.

<img width="502" height="214" alt="Image" src="https://github.com/user-attachments/assets/1ff9b681-3f27-458a-ade9-0b3f3efcf0bf" />
