### ISSUE TITLE
Unable to create users

### ISSUE THREAD

**Issue by etricky** [Finsys/dockhand#28]
Hello
I've installed Dockhand using the following compose file:
```dockerfile
dockhand:
  container_name: dockhand
  image: fnsys/dockhand:latest
  restart: always
  ports:
     -3000:3000
  volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - "/home/dockhand/dockhand_data:/app/data"
``` 
The application is running but when I try to create a new user I always get an error saying it failed to create it. I don't see anything in the docker logs. The documentation also doesn't provide any indication where, within the container, the logs can be obtained. Also, according to the [documentation](https://dockhand.pro/manual/#troubleshooting), there is a script to create an admin user in /app/scripts/emergency/, however:

1. the folder /app/scripts/emergency/ doesn't exist and the scripts are located in /app/scripts/
2. when running the script create-admin.sql, I get an error saying that there is no db in /app/data/dockhand.db which is correct since the db is located in /app/data/**_db_**/dockhand.db
3. I fixed the create-admin.sql in the scripts/sqlite/ folder but, when I run it, I get the below error:
```shell
/app # cd scripts/sqlite/
/app/scripts/sqlite # vi create-admin.sh 
/app/scripts/sqlite # cd ..
/app/scripts # ./create-admin.sh 
========================================
  Dockhand - Create Admin User (SQLite)
========================================

This script will create an admin user with:
  Username: admin
  Password: admin123

If user 'admin' already exists, password will
be reset and admin privileges restored.

Database: /app/data/db/dockhand.db

Continue? [y/N]: y

Creating admin user...
Creating new admin user...
Error: in prepare, table users has no column named is_admin
``` 

Can you advise on which steps I should take to understand why I'm not able to create users?

**Comment by v1rusnl** [comment]
Don't know if thats related, but you got few minor errors in your compose. Try this:

```
dockhand:
  container_name: dockhand
  image: fnsys/dockhand:latest
  restart: always
  ports:
     - 3000:3000      
  volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /home/dockhand/data:/app/data
```

This works without problems on my side.

**Comment by etricky** [comment]
@v1rusnl that is just a typo, apologies for that. The application is up and running and I can create an environment and see all my containers and manage them. It is just when I try to create an user that I have a problem and I get this message. It also doesn't justify why the emergency script is wrong and, when I fixed the correct path, it also doesn't create the admin user as it expects a column that doesn't exist in the users table.

<img width="1640" height="1003" alt="Image" src="https://github.com/user-attachments/assets/9b481bb9-38d6-4c6f-b843-19e20f3437d6" />

**Comment by jotka** [comment]
hi @etricky sorry, i totally forgot to update the emergency scripts and the website manual after database changes, thanks for catching that.

for the UI error, can you try again with this `fnsys/dockhand:937bb936` build? I've added some more debug logging, as i don't see a problem in the code.

**Comment by v1rusnl** [comment]
@jotka Could this be due to missing mail-address when @etricky tries to set up a user? Did not have the problem, only difference between @etricky 's setup and mine is that I gave the user an e-mail.

**Comment by jotka** [comment]
hi @v1rusnl , no, email is optional. I need to see the log output from `fnsys/dockhand:937bb936`

**Comment by etricky** [comment]
Hi @jotka 

I've installed the version you provided and the logs are attached. I do not see any debug logs, is there a specific way I should get the logs?

[_dockhand_logs.txt](https://github.com/user-attachments/files/24395248/_dockhand_logs.txt)

**Comment by v1rusnl** [comment]
I guess you should post the output of the container log when creating a user with the error. Your logs don't seem to look like you did that since there are no entries regarding user creation.

**Comment by etricky** [comment]
Hi @v1rusnl 
Those are all the container logs that I have and I tried to create a user. That is why I asked if there are other logs I should get

**Comment by v1rusnl** [comment]
OK weird. I also set up 937bb936 image and It gives me also no output when creating a user. Thanks for clarification.

**Comment by jotka** [comment]
@etricky open the webbrowser console and see if there is anything there, please. When it fails to create a user.

**Comment by etricky** [comment]
@jotka attached are the console logs

[console-export-2025-12-31_16-21-31.log](https://github.com/user-attachments/files/24396128/console-export-2025-12-31_16-21-31.log)

**Comment by jotka** [comment]
@etricky please test on the latest


`fnsys/dockhand:latest`
`fnsys/dockhand:v1.0.6`

If you still have trouble, I will need to focus on this with some additional debugging, let me know please.

**Comment by etricky** [comment]
@jotka I installed the latest version but I'm still not able to create users. There are no container logs or console browser logs when I try to create it. I also tried to create the container without the local volume but that didn't change anything. 
Let me know if you need anything from my side.

**Comment by jotka** [comment]
hi @etricky 
ok, let's get to the bottom of this. Here's `fnsys/dockhand:77a1bf28`.

  In Docker container logs, you'll see:
  - [CREATE USER] Starting user creation request - confirms request received
  - [CREATE USER] Authorization state: - shows auth status (enabled, authenticated, admin, enterprise)
  - [CREATE USER] Request body: - shows username, email, displayName, password length
  - [CREATE USER] Hashing password... / Password hashed successfully
  - [CREATE USER] Is first user: - whether this is the first user
  - [CREATE USER] Creating user in database...
  - [CREATE USER] Error details: - full error including message, code, constraint, detail, table, column

  In browser console (F12 → Console tab):
  - [CREATE USER] Sending request: - what's being sent
  - [CREATE USER] Response status: - HTTP status code
  - [CREATE USER] Error response: - full error from server

  show the logs when you attempt to create a user, please. Note: this will output a password also so use some dummy, please.

**Comment by etricky** [comment]
Hi @jotka 
Installed the new version and attached are the console logs. There are no container logs for when I tried to create the user

[console-export-2026-1-4_18-12-49.log](https://github.com/user-attachments/files/24423390/console-export-2026-1-4_18-12-49.log)

**Comment by jotka** [comment]
@etricky do you run on synology? this may be related https://github.com/Finsys/dockhand/issues/59

**Comment by etricky** [comment]
Hi @jotka 
I've a mixed setup, I'm running Xpenology which is basically the Synology DSM in a HPE ProLiant MicroServer Gen10 with a AMD Opteron X3216 CPU. According to the issue you mention, the container crashes when creating an user which is not my case, it just shows the error but continues to work properly. 

Looking at the CPU info, it has the AVX flag 

<img width="2228" height="794" alt="Image" src="https://github.com/user-attachments/assets/0961c49f-c282-40cc-a87a-93cf8d8203ef" />

**Comment by jotka** [comment]
@etricky what is the kernel version?

**Comment by etricky** [comment]
Hi @jotka 
It's an old one, 3.10.105. I don't want you to go into the rabbit hole of having to troubleshoot issues caused by old kernel versions. If indeed the kernel is the issue, it's fine if you close this issue with a unsupported justification.

**Comment by jotka** [comment]
> It's an old one

aah. ok, so this is a known issue. i have a duplicate of this somewhere. I **will** support this with some other `random` generator (i think this is the only thing showing the problem on old kernels), but it has a bit lower priority :) And this will be a separate image.

**Comment by jotka** [comment]
hi. I've implemented a crypto fallback for old Linux kernels (<3.17).
can i ask you to try to create a user on this build `docker.io/fnsys/dockhand:335eefc2-baseline` 

also, post the startup log of Dockhand, please - I need to see if it detects the older kernel properly. ✌️

**Comment by etricky** [comment]
Hi Jarek
I've installed that version but the issue still remains. Attached are the container logs.

[dockhand-logs.txt](https://github.com/user-attachments/files/24512091/dockhand-logs.txt)

**Comment by jotka** [comment]
@etricky ok, one more try, please `fnsys/dockhand:5a4608f6-baseline`

**Comment by etricky** [comment]
Hi @jotka 
With this new build I was able to create the user! Thank you so much for your help 👍
